# Generated by Django 4.2.2 on 2023-06-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_alter_bankmodel_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='bnkm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
                ('psw', models.CharField(max_length=20)),
            ],
        ),
    ]
