# Generated by Django 4.2.2 on 2023-06-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_bnkm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bankmodel',
        ),
    ]
