# Generated by Django 4.2.2 on 2023-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_delete_bankmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnkm',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
