# Generated by Django 4.2.2 on 2023-07-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_bnkm_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnkm',
            name='acc_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
