# Generated by Django 4.2.2 on 2023-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_addamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='addamount',
            name='amountadd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
