# Generated by Django 4.2.2 on 2023-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_addamount_amountadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addamount',
            old_name='amount1',
            new_name='amount2',
        ),
        migrations.RemoveField(
            model_name='addamount',
            name='amountadd',
        ),
    ]
