# Generated by Django 4.2.2 on 2023-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_newsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsm',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsm',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
