# Generated by Django 4.2.2 on 2023-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_alter_newsm_content_alter_newsm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addamount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widamount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
