# Generated by Django 4.2.2 on 2023-07-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0013_addamount_uid_widamount_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsm',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
