# Generated by Django 4.2.2 on 2023-07-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_newsm_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsm',
            name='image',
        ),
    ]
