# Generated by Django 4.2.2 on 2023-07-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0016_alter_newsm_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
