# Generated by Django 4.2.2 on 2023-07-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0018_wishlist_delete_tablm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='topic',
            new_name='title',
        ),
    ]
